/*
    날짜: 2025/07/18
    이름: 윤종인
    내용: SQL 연습문제1
*/

--실습 1-1
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER shop IDENTIFIED BY 1234;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO shop;

--실습 1-2
CREATE TABLE customer(
    cid VARCHAR2(20) PRIMARY KEY,
    name VARCHAR2(20) NOT NULL,
    hp CHAR(13) UNIQUE,
    address VARCHAR2(200),
    rdate DATE NOT NULL
);
CREATE TABLE product(
    pno NUMBER(4) PRIMARY KEY,
    pname VARCHAR2(30) NOT NULL,
    stock NUMBER DEFAULT 0,
    price NUMBER,
    company VARCHAR2(20)
);
CREATE TABLE orders(
    ORD_NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORD_CID VARCHAR2(20) NOT NULL,
    ORD_PNO NUMBER(4) NOT NULL,
    ORD_CNT NUMBER DEFAULT 1,
    ORD_DATE DATE NOT NULL
);

--실습 1-3
insert into customer values ('c101','김유신','010-1234-1001','김해시 봉황동','2022-01-01');
insert into customer values ('c102','김춘추','010-1234-1002','경주시 보문동','2022-01-02');
insert into customer values ('c103','장보고','010-1234-1003','완도군 청산면','2022-01-03');
insert into customer values ('c104','강감찬','010-1234-1004','서울시 마포구','2022-01-04');
insert into customer values ('c105','이성계',NULL,NULL,'2022-01-05');
insert into customer values ('c106','정철','010-1234-1006','경기도 용인시','2022-01-06');
insert into customer values ('c107','허준',NULL,NULL,'2022-01-07');
insert into customer values ('c108','이순신','010-1234-1008','서울시 영등포구','2022-01-08');
insert into customer values ('c109','송상현','010-1234-1009','부산시 동래구','2022-01-09');
insert into customer values ('c110','정약용','010-1234-1010','경기도 광주시','2022-01-10');

insert into product values (1,'새우깡',5000,1500,'농심');
insert into product values (2,'초코파이',2500,2500,'오리온');
insert into product values (3,'포카칩',3600,1700,'오리온');
insert into product values (4,'양파링',1250,1800,'농심');
insert into product values (5,'죠리퐁',2200,NULL,'크라운');
insert into product values (6,'마가렛트',3500,3500,'롯데');
insert into product values (7,'뿌셔뿌셔',1650,1200,'오뚜기');

insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c102',3,2,'2022-07-01 13:15:10');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c101',4,1,'2022-07-01 14:16:11');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c108',1,1,'2022-07-01 17:23:18');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c109',6,5,'2022-07-02 10:46:36');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c102',2,1,'2022-07-03 09:15:37');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c101',7,3,'2022-07-03 12:35:12');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c110',1,2,'2022-07-03 16:55:36');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c104',2,4,'2022-07-04 14:23:23');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c102',1,3,'2022-07-04 21:54:34');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values ('c107',6,1,'2022-07-05 14:21:03');

--실습 1-4
select * from customer;

--실습 1-5
select cid,name,hp from customer;

--실습 1-6
select * from product;

--실습 1-7
select company from product;

--실습 1-8
select distinct company from product;

--실습 1-9
select pname,price from product;

--실습 1-10
select pname,price+500 as 조정단가 from product;

--실습 1-11
select pname,stock,price from product where company = '오리온';

--실습 1-12
select ord_pno,ord_cnt,ord_date from orders where ord_cid = 'c102';

--실습 1-13
select ord_pno,ord_cnt,ord_date from orders where ord_cid = 'c102' and ord_cnt >= 2;

--실습 1-14
select * from product where price between 1000 and 2000;

--실습 1-15
select cid,name,hp,address from customer where name like '김%';

--실습 1-16
select cid,name,hp,address from customer where name like '__';

--실습 1-17
select * from customer where hp is null;

--실습 1-18
select * from customer where address is not null;

--실습 1-19
select * from customer order by rdate desc;

--실습 1-20
select * from orders where ord_cnt >= 3 order by ord_cnt desc,ord_pno;

--실습 1-21
select avg(price) from product;

--실습 1-22
select sum(stock) as "재고량 합계" from product where company='농심';

--실습 1-23
select count(*) as 고객수 from customer;

--실습 1-24
select count(distinct company) as "제조업체 수" from product;

--실습 1-25
select ord_pno as "주문 상품번호",sum(ord_cnt) as "총 주문수량" from orders group by ord_pno order by ord_pno;

--실습 1-26
select company as 제조업체,count(*) as 제품수,max(price) as 최고가 from product group by company order by company;

--실습 1-27
select company as 제조업체,count(*) as 제품수,max(price) as 최고가 from product group by company having count(*)>=2;

--실습 1-28
select ord_pno,ord_cid,sum(ord_cnt) as "총 주문수량" from orders group by ord_pno, ord_cid order by ord_pno;

--실습 1-29
select ord_cid,pname from orders a join product b on a.ord_pno = b.pno where ord_cid = 'c102';

--실습 1-30
select ord_cid,name,pname,ord_date from orders a join customer b on a.ord_cid = b.cid join product c on a.ord_pno = c.pno where ord_date like '2022-07-03%';